baseURL = "https://knowledge.arne.me/"
languageCode = "en-us"
title = "Arnes Knowledge"
theme = "cortex"
pygmentsUseClasses = true

[params]
email = "hallo@arne.me"
footer = "Built with ♥ with Org-mode and Hugo."
repo = "https://github.com/bahlo/knowledge"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "friendly"
    tabWidth = 4
