#+title: 99 Additional Bits of Unsolicited Advice
#+date: 2021-06-02

[[file:kevin-kelly.org][Kevin Kelly]] shares even more [[file:wisdom.org][Wisdom]] in his second unsolicited advice blogpost [[https://kk.org/thetechnium/99-additional-bits-of-unsolicited-advice/][99 Additional Bits of Unsolicited Advice]]:

#+begin_quote
I have another birthday, and another bunch of unsolicited advice.
#+end_quote

These are the things that resonated with me at the time of writing this:

- That thing that made you weird as a kid could make you great as an adult — if you don’t lose it.
- If you have any doubt at all about being able to carry a load in one trip, do yourself a huge favor and make two trips.
- Recipe for success: under-promise and over-deliver.
- It’s not an apology if it comes with an excuse. It is not a compliment if it comes with a request.
- If something fails where you thought it would fail, that is not a failure.
- Be governed not by the tyranny of the urgent but by the elevation of the important.
- In all things — except love — start with the exit strategy. Prepare for the ending. Almost anything is easier to get into than out of.
- Don’t aim to have others like you; aim to have them respect you.
- The foundation of maturity: Just because it’s not your fault doesn’t mean it’s not your responsibility.
- A multitude of bad ideas is necessary for one good idea.
- If you can avoid seeking approval of others, your power is limitless.
- To be wealthy, accumulate all those things that money can’t buy.
- Be the change you wish to see.
- Don’t loan money to a friend unless you are ready to make it a gift.
- If you borrow something, try to return it in better shape than you received it. Clean it, sharpen it, fill it up.
- Writing down one thing you are grateful for each day is the cheapest possible therapy ever.
- When someone tells you something is wrong, they’re usually right. When someone tells you how to fix it, they’re usually wrong.
- Avoid hitting the snooze button. That’s just training you to oversleep.
- Always say less than necessary.
- Each time you reach out to people, bring them a blessing; then they’ll be happy to see you when you bring them a problem.
- Bad things can happen fast, but almost all good things happen slowly.
- You can reduce the annoyance of someone’s stupid belief by increasing your understanding of why they believe it.
- If your goal does not have a schedule, it is a dream.
- All the greatest gains in life — in wealth, relationships, or knowledge —come from the magic of compounding interest — amplifying small steady gains. All you need for abundance is to keep adding 1% more than you subtract on a regular basis.
- I have never met a person I admired who did not read more books than I did.
- The greatest teacher is called “doing”.
- A problem that can be solved with money is not really a problem.
- When you are stuck, sleep on it. Let your subconscious work for you.
- Children totally accept — and crave — family rules. “In our family we have a rule for X” is the only excuse a parent needs for setting a family policy. In fact, “I have a rule for X” is the only excuse you need for your own personal policies.
- This is the best time ever to make something. None of the greatest, coolest creations 20 years from now have been invented yet. You are not late.
- Every person you meet knows an amazing lot about something you know virtually nothing about. Your job is to discover what it is, and it won’t be obvious.
- Always give credit, take blame.
- Be frugal in all things, except in your passions splurge.
- When making something, always get a few extras — extra material, extra parts, extra space, extra finishes. The extras serve as backups for mistakes, reduce stress, and fill your inventory for the future. They are the cheapest insurance.
