#+TITLE: Expiring vs. Permanent Skills

Morgan Housel shares some [[file:wisdom.org][Wisdom]] in a [[https://www.collaborativefund.com/blog/expiring-vs-permanent-skills/][blogpost]], saying every field has two kinds of skills: expiring and permanent.

* Expiring skills
Expiring skills are vital at a given time but prone to disminishing as technology improves and a field evolves

They tend to get more attention, are more likely to be the "cool thing".

* Permanent skills
Permanent were as essential 100 years ago as they are today, and will still be 100 years from now.

Their age make them look stale and basic, they are hard to define and quantify. But they are compound over time. When you spend a lifetime perfecting one skill whose importance never wanes, the payoffs can be ridiculous.

** Examples
- Not being a jerk
- The willingness to adapt views you wish were permanent
- Getting along with people you disagree with
- Getting to the point
- Respecting luck as much as you respect risk
- Staying out of the way as much as you offer to help
- Accepting a certain degree of hassle and nonsense when reality demands it
- The ability to distinguish "temporarily out of favor" from wrong
