#+TITLE: Gifting Holy Trinity

Ven Neistat, a.k.a. The Spirited Man, shared his perspective on gifts in the video [[https://youtu.be/WqYIkm66RSI][The "GIFTING HOLY TRINITY" & More ]] and it's great.

Here's my summary:

1. All gifts should contain an element of surprise
   If they know what they're getting, surprise them with =when= or =how=.
2. Respect the gifting Holy Trinity: Nice, Made & Thoughtful
   Pick at least 2.
3. Made gifts should not bebigger than one's hand
   If they hate your gift you don't waste their real estate.
4. Dating and/or monogramming a gift gives it extra power.
   Get a wood burner, engraver and whiteout pen.
5. Know what flowers your girl likes.
   Go to a flower shop
6. Take your time with books.
   Date and write your name in one of the leaves of the book
7. A postcard counts
   Add a drawing, a poem, a joke, make it custom
8. Two days
   First day to think about it, sleep on it, then buying it.
9. She will tell you
   Write it down when she mentions it, pay attention
10. Buy small gifts when you travel.
    Even if you don't know who it's for.
11. Expensive, not costly
    10 $ chocolate is expensive, but it's not a lot of money.
12. For kids: You pick the store, the kid picks the gift.

Send thank you notes!
