#+TITLE: Gifting Holy Trinity

Ven Neistat, a.k.a. The Spirited Man, shared his perspective on gifts in the video [[https://youtu.be/WqYIkm66RSI][The GIFTING HOLY TRINITY & More ]] and it's great.

* Summary
These are the points made in the video:
** All gifts should contain an element of surprise
If they know what they're getting, surprise them with =when= or =how=.
** Respect the gifting Holy Trinity: Nice, Made & Thoughtful
Pick at least 2.
** Made gifts should not bebigger than one's hand
	If they hate your gift you don't waste their real estate.
** Dating and/or monogramming a gift gives it extra power.
Get a wood burner, engraver and whiteout pen.
** Know what flowers your girl likes.
Go to a flower shop
** Take your time with books.
Date and write your name in one of the leaves of the book
** A postcard counts
Add a drawing, a poem, a joke, make it custom
** Two days
First day to think about it, sleep on it, then buying it.
** She will tell you
Write it down when she mentions it, pay attention
** Buy small gifts when you travel.
Even if you don't know who it's for.
** Expensive, not costly
10 $ chocolate is expensive, but it's not a lot of money.
** For kids: You pick the store, the kid picks the gift.

And send thank you notes!
