#+title: Rclone

- url :: [[https://rclone.org][rclone.org]]
- tags :: [[file:sysops.org][SysOps]]

The Swiss army knife of cloud storage.

Rclone is a command line program to manage files on cloud storage. It supports lots of cloud providers and encryption.

* Use cases
There is /a lot/ you can do with rclone so this is just a list of things that might be useful to you.

** Encrypted backup
*** Create remote
The first thing you want to do is set up a remote (storage), run the following:
#+begin_src sh
$ rclone config
#+end_src

It will present a wizard, press =n= to create a new one, then follow the steps to set up your storage.

*** Encrypted remote
To be able to use encryption we need to add another remote, follow the steps again but choose =crypt= as storage. I recommend using the same name as for the first remote but appending =-secret=.

It will ask you to enter a remote to encrypt/decrypt. Enter the name of the storage we created first. Then follow the wizard to completion.

*** The backup
You can run the following to run a backup right now:
#+begin_src sh
$ rclone sync /local/path my-remote-secret:
#+end_src

If you want to run the backup regulary you can create a [[file:cron.org][cron]] job. The ~flock~ command makes sure only one backup can run at the time.

#+begin_src sh
,* 2 * * * flock --no-fork --exclusive --nonblock /var/lock/rclone-media.lock -c 'rclone sync /local/path my-remote-secret: > /var/log/rclone-media.log'
#+end_src
