#+TITLE: Rclone

[[https://rclone.org][Rclone]] is a command line program to manage files on cloud storage.
It supports lots of cloud providers and encryption.
It's often used by [[file:sysops.org][SysOps]] teams.

* Use cases
There is /a lot/ you can do with rclone so this is just a list of things that might be useful to you.

** Encrypted backup
*** Create remote
The first thing you want to do is set up a remote (storage), run the following:
#+BEGIN_SRC sh
$ rclone config
#+END_SRC

It will present a wizard, press =n= to create a new one, then follow the steps to set up your storage.

*** Encrypted remote
To be able to use encryption we need to add another remote, follow the steps again but choose =crypt= as storage. I recommend using the same name as for the first remote but appending =-secret=.

It will ask you to enter a remote to encrypt/decrypt. Enter the name of the storage we created first. Then follow the wizard to completion.

*** The backup
You can run the following to run a backup right now:
#+BEGIN_SRC sh
$ rclone sync /local/path my-remote-secret:
#+END_SRC

If you want to run the backup regulary you can create a [[file:cron.org][cron]] job. The ~flock~ command makes sure only one backup can run at the time.

#+BEGIN_SRC sh
,* 2 * * * flock --no-fork --exclusive --nonblock /var/lock/rclone-media.lock -c 'rclone sync /local/path my-remote-secret: > /var/log/rclone-media.log'
#+END_SRC
