name: Build

on:
  push:
    branches:
      - main

env:
  HUGO_VERSION: 0.74.3
  EMACS_VERSION: 27.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install org-roam dependencies
        run: |
          sudo apt-get install sqlite3
      - name: Install emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ env.EMACS_VERSION }}
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true
      - name: Create static folder
        run: mkdir -p static
      - name: Convert org files to hugo
        run: make org2hugo
      - name: Generate site
        run: make hugo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: site

