name: Build

on:
  push:
    branches:
      - main

env:
  HUGO_VERSION: 0.74.3
  EMACS_VERSION: 27.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install org-roam dependencies
        run: |
          sudo apt-get install sqlite3
      - name: Install emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ env.EMACS_VERSION }}
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true
      - name: Create static folder
        run: mkdir -p static
      - name: Convert org files to hugo
        run: make org2hugo
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install subset dependencies
        run: |
          npm install -g glyphhanger
          pip3 install fonttools brotli zopfli
      - name: Subset fonts
        run: |
          # Start hugo and note pid
          hugo serve --port 1313 &
          echo $! > /tmp/hugo-pid

          # Generate subset fonts
          # We do a pretty wonky parsing of sitemap.xml
          glyphhanger $(curl -s http://localhost:1313/sitemap.xml | grep loc | sed 's/\s*<loc>//' | sed 's/<\/loc>//' | tr '\n' ' ') --family="Inter" --formats=woff2,woff --subset="./fonts/inter/*.woff2"
          glyphhanger $(curl -s http://localhost:1313/sitemap.xml | grep loc | sed 's/\s*<loc>//' | sed 's/<\/loc>//' | tr '\n' ' ') --family="iosevka web" --formats=woff2,woff --subset="./fonts/iosevka/*.woff2"

          # Kill hugo
          kill -9 "$(cat /tmp/hugo-pid)"

          # Move subset fonts to static/fonts to override theme
          mkdir -p static/fonts
          mv ./fonts/inter/*-subset.* ./static/fonts/
          for file in ./static/fonts/Inter-*-subset.*; do mv "$file" ${file/-subset/}; done
          mv ./fonts/iosevka/*-subset.* ./static/fonts/
          for file in ./static/fonts/iosevka-*-subset.*; do mv "$file" ${file/-subset/}; done
      - name: Generate site
        run: make hugo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: netlify

